spring:
  application:
    name: ms-cuentas

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cuentas_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


ms:
  clientes:
    url: ${MS_CLIENTES_URL:http://localhost:8080/api}

server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /api

logging:
  level:
    com.example.cuentas: DEBUG
    org.hibernate.SQL: DEBUG
